#!/bin/bash

#ddev-generated

echo "Configuring InVRT for $DDEV_HOSTNAME"

ddev invrt-device > "$DDEV_APPROOT/.ddev/.invrt/devices.yaml"
ddev invrt-environment > "$DDEV_APPROOT/.ddev/.invrt/environments.yaml"
ddev invrt-profile > "$DDEV_APPROOT/.ddev/.invrt/profiles.yaml"