#!/bin/bash

#ddev-generated

echo "Tearing down InVRT users for $DDEV_HOSTNAME"

username=$(ddev invrt config "$@" | grep username | awk '{print $2}')
password=$(ddev invrt config "$@" | grep password | awk '{print $2}')

if [[ -n "$username" && -n "$password" ]]; then
  ddev drush user:cancel "$username" --delete-content --yes
else
  echo "No credentials found. No users will be set up."
fi