#!/bin/bash

#ddev-generated

if [ $DDEV_PROJECT_TYPE == "drupal11" ]; then
  echo "# Drupal theme breakpoints from $DDEV_PROJECT"
  ddev drush php:script .ddev/invrt-build/drupal-breakpoints.php
elif [ $DDEV_PROJECT_TYPE == "wordpress" ]; then
  echo "# No device sizes detected for wordpress"
elif [ $DDEV_PROJECT_TYPE == "backdrop" ]; then
  echo "# No device sizes detected for backdrop"
fi